[package]
name = "gamecrab"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
overflow-checks = false

[dependencies]
crossterm = "0.27.0"
gl = "0.14.0"
memmap2 = "0.9.0"
sdl2 = "0.36.0"
stopwatch = "0.0.7"
